# plugins:
#   - jekyll-default-layout

collections:
  pages:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "page" 
      # might want to change layout to default if website structure changes
      # for now everything, including index.md, is a page