# plugins:
#   - jekyll-feed

collections:
  musings:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "musings"
    values:
      layout: "musing"
  - scope:
      path: ""
    values:
      layout: "musing" 
      # might want to change layout to default if website structure changes
      # for now everything, including index.md, is a musing

author: cc
url: https://lazysomedays.com
# title: 
# description:
# feed:
#   icon: /images/icon.png
#   logo: /images/logo.png